"""
Django settings for ecomerce project.

Generated by 'django-admin startproject' using Django 2.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ')c1=w68j$(gy63$t*n553w)6sdjo01)=*$+sc5dov@%qi6_)hl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
#'pruebamultimotoresgemca.herokuapp.com ' ,  
ALLOWED_HOSTS = ['pruebamultimotoresgemca.herokuapp.com' , 'localhost'] 

#datos para decirle que estoy usando un modelo de usuario que yo cree
AUTH_USER_MODEL = 'usuarios.User'
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'vestas_usuario',
    'usuarios',
    'carro',
    'submenu',
    'crispy_forms',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'django_inlinecss',
    'social_django',
    

    

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'ecomerce.middleware.ProfileCompletionMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
]

ROOT_URLCONF = 'ecomerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {

            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'carro.context_processor.importe_total_carro',
                'social_django.context_processors.backends',  
                'social_django.context_processors.login_redirect',
            ],



            
        },

        
    },
]





AUTHENTICATION_BACKENDS=[

    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
    'social_core.backends.facebook.FacebookOAuth2',

]

WSGI_APPLICATION = 'ecomerce.wsgi.application'

"""DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}"""


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'dq2m55g0tqg17',
        'USER' : 'anzztyzklfjkvg',
        'PASSWORD': 'ac3ab0c5bbe50d81d7b9c72e5198a3fb1ff4c63b3db0b1904ff5377a7217963e',
        'HOST': 'ec2-52-1-20-236.compute-1.amazonaws.com',
        'PORT' : '5432',
    }
}
 







# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/





STATIC_URL = '/static/'
STATICFILES_DIRS=(os.path.join(BASE_DIR , 'static'),)



MEDIA_ROOT = os.path.join(BASE_DIR ,'media')
MEDIA_URL = '/media/'



EMAIL_BACKEND="django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST="smtp.gmail.com"
EMAIL_USE_TLS=True 
EMAIL_PORT=587
EMAIL_HOST_USER="angelourbannoo@gmail.com"
EMAIL_HOST_PASSWORD="angelo2021"




SITE_ID=2
LOGIN_URL = 'login' 
LOGIN_REDIRECT_URL = 'home'

SOCIALACCOUNT_PROVIDERS={
    
    'google':{
        'SCOPE':[
            'profile',
            'email',


            ],
            'AUTH_PARAMS':{
                'access_type': 'online',
            }
    },

    'facebook': {
        'METHOD': 'oauth2',
        'SCOPE': ['email', 'public_profile'],
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'INIT_PARAMS': {'cookie': True},
        'FIELDS': [
            'id',
            'email',
            'name',
            'first_name',
            'last_name',
            'verified',
            'locale',
            'timezone',
            'link',
            'gender',
            'updated_time',
        ],
        'EXCHANGE_TOKEN': True,
        'VERIFIED_EMAIL': False,
        'VERSION': 'v2.10',
    }


    




}