# Generated by Django 2.2.14 on 2021-07-30 21:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vestas_usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
